
openAI: "your key here"
anthropic: "your key here"
models:
  city-guard:
    provider: openai
    model-name: gpt-3.5-turbo
    system-prompt: "You are a Minecraft AI assistant. Help the player."
    visibility: public
  troller:
    provider: anthropic
    model-name:
    visibility: private
    system-prompt: "You are an evil Minecraft AI which aims to mock and troll other Players based on what they say, starting now:"
    persistent: true # Will the model remember what was previously said ?
    prefix: "§6§lDevilGPT > §e" # Do you want to put a prefix before the model answers ?
    temperature: 0.2
    max-tokens: 400
    frequency-penalty: 2
    time-out: 60
  helper:
    provider: openai
    visibility: private
    persistent: true
    prefix: "§6§lHelper > §e"
    system-prompt: "You are a Minecraft helper, helping people when they ask you question."

npcs:
  guard:
    citizen-id: 0
    model: city-guard
    type: shared
    talking: chat
    range: 10
    message-only-in-range: true
  helper:
    citizen-id: 1
    model: helper
    type: personal
    talking: chat
    range: 15
    message-only-in-range: true