name: LLM-craft
version: '${project.version}'
main: fr.yro.llmcraft.LLM_craft
api-version: '1.20'
author: Yro
soft-depend: [DecentHolograms, Citizens, LuckPerms]
commands:
  ask:
    description: Ask/Talk to a model.
    usage: /ask <model> <your prompt>
    permission: llmcraft.ask
  listen:
    description: Listen the next x times a player speaks, and answers to him using the model.
    usage: /listen <player> <model> <number of times>
    permission: llmcraft.listen
  instance:
    description: create a new instance of the specified model type.
    usage: /instance <model type> <identifier>
    permission: llmcraft.instance
  llmcraft:
    description: "§aLlm-craft help command"
    usage: "§a/llmcraft"
    permission: llmcraft.help
  model:
    description: "Get info on a model"
    usage: "§a/model <type>"
    permission: llmcraft.model
  models:
    description: "Get info on a model"
    usage: "§a/model <type>"
    permission: llmcraft.models
  modeltype:
    description: "Get info on a model type"
    usage: "§a/model <type>"
    permission: llmcraft.modeltype
  modeltypes:
    description: "Get info on a model type"
    usage: "§a/modeltypes <type>"
    permission: llmcraft.modeltype
## Limiter commands
  limits:
    description: "Get info on a model type's usage limitations"
    usage: "§a/limits <type>"
    permission: llmcraft.limits
  limit:
    description: "Get info on a model type's usage limitations"
    usage: "§a/limits <type>"
    permission: llmcraft.limits
  limiter:
    description: "Get info on a model type's usage limitations"
    usage: "§a/limits <type>"
    permission: llmcraft.limits
  limiters:
    description: "Get info on a model type's usage limitations"
    usage: "§a/limits <type>"
    permission: llmcraft.limits